"""initial schema

Revision ID: 64cddc323b5b
Revises: 
Create Date: 2026-08-03 12:46:07.795879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cddc323b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('composers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'year', name='uq_film_name_year')
    )
    op.create_table('lyricists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vocalists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'film_id', name='uq_song_title_film')
    )
    op.create_table('song_actors',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'actor_id')
    )
    op.create_table('song_composers',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'composer_id')
    )
    op.create_table('song_lyricists',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('lyricist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lyricist_id'], ['lyricists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'lyricist_id')
    )
    op.create_table('song_vocalists',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('vocalist_id', sa.Integer(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['vocalist_id'], ['vocalists.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'vocalist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_vocalists')
    op.drop_table('song_lyricists')
    op.drop_table('song_composers')
    op.drop_table('song_actors')
    op.drop_table('songs')
    op.drop_table('vocalists')
    op.drop_table('lyricists')
    op.drop_table('films')
    op.drop_table('composers')
    op.drop_table('actors')
    # ### end Alembic commands ###
